CREATE TABLE USUARIOS(
NOMBRE_USUARIO VARCHAR2(20) NOT NULL,
CONTRASEÑA VARCHAR2(15) NOT NULL,
DOMICILIO_SOCIAL VARCHAR2(40) NOT NULL,
CREADO_EN DATE DEFAULT SYSDATE+1,
CORREO_CLIENTE VARCHAR2(20) NOT NULL,
ID_USER NUMBER(10) PRIMARY KEY
);

CREATE TABLE CLIENTES(
ID_CLIENTE NUMBER(10) PRIMARY KEY,
ID_USER NUMBER(10) PRIMARY KEY,
CORREO_CLIENTE VARCHAR2(20) NOT NULL,
TIPO VARCHAR2(20),
TELEFONO NUMBER(9) NOT NULL,
DOMICILIO VARCHAR2(40),
FECHA_CREA DATE DEFAULT SYSDATE+1,
ID_USER VARCHAR2(20) NOT NULL,
FOREIGN KEY (ID_USER) REFERENCES USUARIOS ON DELETE CASCADE
);
CREATE TABLE FACT_PRES(
ID_USER NUMBER(10) NOT NULL,
ID_CLIENTE NUMBER(10) NOT NULL,
PORC_DESC NUMBER(2),
PORC_MATERIAL NUMBER(2),
PORC_IVA NUMBER(2),
FECHA_CREACION DATE DEFAULT SYSDATE+1,
ID_FACTPRES NUMBER(10) PRIMARY KEY,
NUMERO NUMBER(10),
BASTIDOR VARCHAR2 (10),
TOTAL NUMBER(5,2),
MATRICULA VARCHAR2(7),
TIPO VARCHAR2(15),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES ON DELETE CASCADE,
FOREIGN KEY(ID_USER)REFERENCES USUARIOS ON DELETE CASCADE
);
CREATE TABLE APARECEN(
ID_FACTPRES NUMBER(10) PRIMARY KEY,
NOMBRE_PIEZA VARCHAR2(20)PRIMARY KEY,
FOREIGN KEY(ID_FACTPRES)REFERENCES FACT_PRES ON DELETE CASCADE,
FOREIGN KEY(NOMBRE_PIEZA)REFERENCES PIEZAS ON DELETE CASCADE
);
CREATE TABLE GOLPES(
TAMAÑO NUMBER(10,3) PRIMARY KEY,
CANTIDAD NUMBER(10),
NOMBRE_PIEZA VARCHAR2(20),
FOREIGN KEY(NOMBRE_PIEZA)REFERENCES PIEZAS ON DELETE CASCADE
);
CREATE TABLE PIEZAS(
PINTURA VARCHAR2(20),
TIPO VARCHAR2(20),
NOMBRE_PIEZA VARCHAR2(20) PRIMARY KEY,
COLA ---
);
CREATE TABLE VEHICULO(
ID_VEHICULO NUMBER(10) PRIMARY KEY,
MODELO VARCHAR2(20),
MARCA VARCHAR2(20),
MOTORIZACION ---,
SEGMENTO ---
);
CREATE TABLE FORMAN(
NOMBRE_PIEZA VARCHAR2(20) PRIMARY KEY,
ID_VEHICULO NUMBER(10) PRIMARY KEY,
FOREIGN KEY(NOMBRE_PIEZA)REFERENCES PIEZAS ON DELETE CASCADE,
FOREIGN KEY(ID_VEHICULO)REFERENCES VEHICULO ON DELETE CASCADE
);
CREATE TABLE AUTONOMO(
NOMBRE_AUTO VARCHAR2(30),
NIF VARCHAR2(10),
ID_USER NUMBER(10),
FOREIGN KEY(ID_USER) REFERENCES USUARIOS ON DELETE CASCADE
);
CREATE TABLE EMPRESA(
RAZON_SOCIAL VARCHAR2(30),
CIF VARCHAR2(10),
ID_USER NUMBER(10),
FOREIGN KEY(ID_USER) REFERENCES USUARIOS ON DELETE CASCADE
);